export const translations = {
  esp: {
    agencies: "Agencias",
    agency: "Agencia",
    alwaysAvailable:
      "Nuestro equipo está siempre disponible para ayudarte en cada paso del camino",
    buyEverywhere: "Buy Everywhere",
    cancel: "Cancelar",
    categories: "Categorías",
    choosePerfectPlan: "Elige tu plan perfecto",
    chooseTemplates:
      "Elige entre una variedad de templates prediseñadas y personalizables",
    confirmDeleteAgencies:
      "Estás seguro/a de querer eliminar las agencias seleccionadas?",
    confirmDeleteAgency: "Estás seguro/a de querer eliminar la agencia",
    confirmDeletePlan: "Estás seguro/a de querer eliminar el plan",
    confirmDeletePlans:
      "Estás seguro/a de querer eliminar los planes seleccionados?",
    contacts: "Contactos",
    createAccount: "Crea tu cuenta",
    createPlan: "Crea un plan",
    createYourOnlineStore: "Crea tu tienda online con Mangoes",
    customizeStore: "Personaliza tu tienda",
    dashboard: "Dashboard",
    dashboardImageAlt: "Mangoes Dashboard",
    deaconDesigner: "Deacon Diseñadora",
    delete: "Eliminar",
    deleteAgencies: "Eliminar agencias",
    deletePlans: "Eliminar planes",
    edit: "Editar",
    easyToUse: "Fácil de usar",
    export: "Exportar",
    features: "Servicios",
    featuresDescription: "¿Por qué elegir Mangoes?",
    filterByName: "Filtrar por nombre",
    generateReceipts:
      "Genera comprobantes internos de compra y venta al instante para un registro organizado de tus transacciones.",
    goToWebsite: "Ir a la página",
    home: "Inicio",
    howItWorks: "Cómo funciona",
    inventory: "Inventario",
    inventoryManagement: "Gestión de inventario",
    inventorySystem:
      "Nuestro aplicación tiene integrada un sistema de gestión de inventario ideal para vos.",
    intuitiveInterface:
      "Interfaz intuitiva que te permite crear y gestionar tu tienda sin conocimientos técnicos",
    launchBusiness: "¡Lanza tu negocio online!",
    launchpad: "Launchpad",
    manageOrders:
      "Gestiona fácilmente todas tus órdenes de compra y venta llevando un control detallado de todos tus movimientos comerciales.",
    mangoes: "Mangoes",
    name: "Nombre",
    next: "Siguiente",
    noResults: "No se encontraron resultados",
    of: "de",
    perfectPlatform:
      "La plataforma perfecta para pymes y emprendedores que quieren llevar su negocio al siguiente nivel",
    plan: "Plan",
    plans: "Planes",
    previous: "Anterior",
    pricing: "Precios",
    pricingDescription:
      "Nuestros planes están diseñados para ofrecerte las herramientas y el soporte que necesitas para hacer crecer tu negocio. Ya sea que estés comenzando o busques expandir tu empresa, tenemos la opción perfecta para ti. Elige el plan que mejor se adapte a tus necesidades y empieza a disfrutar de los beneficios desde el primer día.",
    professionalDesigns: "Diseños profesionales",
    products: "Productos",
    publishAndSell:
      "Publica tu tienda y empieza a vender a clientes de todo el país",
    purchaseOrders: "Órdenes de Compra/Venta",
    purchaseReceipts: "Comprobantes de Compra/Venta",
    purchases: "Egresos",
    purchasesInvoices: "Facturas de compra",
    refreshTable: "Actualizar tabla",
    registerAndChoosePlan:
      "Regístrate en Mangoes y elige el plan que mejor se adapte a tus necesidades",
    sales: "Ingresos",
    salesInvoices: "Facturas de venta",
    search: "Buscar",
    selected: "Seleccionado",
    selectTemplate:
      "Selecciona una template y personalízala con tus productos y agencia",
    settings: "Configuración",
    signIn: "Iniciar sesión",
    signUp: "Crear cuenta",
    showing: "Mostrando",
    someBusinessesUsing: "Algunas empresas que están usando Mangoes",
    startNow: "Comenzar",
    support247: "Soporte 24/7",
    team: "Equipo",
    to: "a",
    toolsOtol: "Herramientas OTOL",
    whyChoose: "¿Por qué elegir Mangoes?",
  },
  eng: {
    agencies: "Agencies",
    agency: "Agency",
    alwaysAvailable:
      "Our team is always available to assist you every step of the way",
    buyEverywhere: "Buy Everywhere",
    cancel: "Cancel",
    categories: "Categories",
    choosePerfectPlan: "Choose your perfect plan",
    chooseTemplates:
      "Choose from a variety of pre-designed and customizable templates",
    confirmDeleteAgencies:
      "Are you sure you want to delete the selected agencies?",
    confirmDeleteAgency: "Are you sure you want to delete the agency",
    confirmDeletePlan: "Are you sure you want to delete the plan",
    confirmDeletePlans: "Are you sure you want to delete the selected plans?",
    contacts: "Contacts",
    createAccount: "Create your account",
    createPlan: "Create a plan",
    createYourOnlineStore: "Create your online store with Mangoes",
    customizeStore: "Customize your store",
    dashboard: "Dashboard",
    dashboardImageAlt: "Mangoes Dashboard",
    deaconDesigner: "Deacon Designer",
    delete: "Delete",
    deleteAgencies: "Delete agencies",
    deletePlans: "Delete plans",
    edit: "Edit",
    easyToUse: "Easy to use",
    export: "Export",
    features: "Features",
    featuresDescription: "Why choose Mangoes?",
    filterByName: "Filter by name",
    generateReceipts:
      "Generate internal purchase and sales receipts instantly for an organized record of your transactions.",
    goToWebsite: "Go to website",
    home: "Home",
    howItWorks: "How it works",
    inventory: "Inventory",
    inventoryManagement: "Inventory management",
    inventorySystem:
      "Our app includes an integrated inventory management system ideal for you.",
    intuitiveInterface:
      "Intuitive interface that lets you create and manage your store without technical knowledge",
    launchBusiness: "Launch your online business!",
    launchpad: "Launchpad",
    manageOrders:
      "Easily manage all your purchase and sales orders with detailed tracking of your business transactions",
    mangoes: "Mangoes",
    name: "Name",
    next: "Next",
    noResults: "No results found",
    of: "of",
    perfectPlatform:
      "The perfect platform for SMEs and entrepreneurs looking to take their business to the next level",
    plan: "Plan",
    plans: "Plans",
    previous: "Previous",
    pricing: "Pricing",
    pricingDescription:
      "Our plans are designed to provide you with the tools and support you need to grow your business. Whether you're just starting out or looking to expand your company, we have the perfect option for you. Choose the plan that best suits your needs and start enjoying the benefits from day one.",
    professionalDesigns: "Professional designs",
    products: "Products",
    publishAndSell:
      "Publish your store and start selling to customers nationwide",
    purchaseOrders: "Purchase/Sales Orders",
    purchaseReceipts: "Purchase/Sales Receipts",
    purchases: "Expenses",
    purchasesInvoices: "Purchase invoices",
    refreshTable: "Refresh table",
    registerAndChoosePlan:
      "Register on Mangoes and choose the plan that best suits your needs",
    sales: "Revenue",
    salesInvoices: "Sales invoices",
    search: "Search",
    selected: "Selected",
    selectTemplate:
      "Select a template and customize it with your products and agency",
    settings: "Settings",
    signIn: "Login",
    signUp: "Create account",
    showing: "Showing",
    someBusinessesUsing: "Some businesses using Mangoes",
    startNow: "Start now",
    support247: "Support 24/7",
    team: "Team",
    to: "to",
    toolsOtol: "OTOL Tools",
    whyChoose: "Why choose Mangoes?",
  },
  por: {
    agencies: "Agências",
    agency: "Agência",
    alwaysAvailable:
      "Nossa equipe está sempre disponível para ajudá-lo em cada etapa do caminho",
    buyEverywhere: "Compre em qualquer lugar",
    cancel: "Cancelar",
    categories: "Categorias",
    choosePerfectPlan: "Escolha o plano perfeito",
    chooseTemplates:
      "Escolha entre uma variedade de modelos pré-desenhados e personalizáveis",
    confirmDeleteAgencies:
      "Tem certeza de que deseja excluir as agências selecionadas?",
    confirmDeleteAgency: "Tem certeza de que deseja excluir a agência",
    confirmDeletePlan: "Tem certeza de que deseja excluir o plano?",
    confirmDeletePlans:
      "Tem certeza de que deseja excluir os planos selecionados?",
    contacts: "Contatos",
    createAccount: "Crie sua conta",
    createPlan: "Crie um plano",
    createYourOnlineStore: "Crie sua loja online com Mangoes",
    customizeStore: "Personalize sua loja",
    dashboard: "Dashboard",
    dashboardImageAlt: "Dashboard do Mangoes",
    deaconDesigner: "Deacon Designer",
    delete: "Excluir",
    deleteAgencies: "Excluir agências",
    deletePlans: "Excluir planos",
    edit: "Editar",
    easyToUse: "Fácil de usar",
    export: "Exportar",
    features: "Serviços",
    featuresDescription: "Por que escolher o Mangoes?",
    filterByName: "Filtrar por nome",
    generateReceipts:
      "Gere recibos internos de compras e vendas instantaneamente para um registro organizado de suas transações.",
    goToWebsite: "Ir para o site",
    home: "Home",
    howItWorks: "Como funciona",
    inventory: "Inventário",
    inventoryManagement: "Gerenciamento de inventário",
    inventorySystem:
      "Nosso aplicativo inclui um sistema integrado de gerenciamento de inventário ideal para você.",
    intuitiveInterface:
      "Interface intuitiva que permite criar e gerenciar sua loja sem conhecimento técnico",
    launchBusiness: "Lance seu negócio online!",
    launchpad: "Launchpad",
    manageOrders:
      "Gerencie facilmente todos os seus pedidos de compra e venda com um controle detalhado de todas as suas transações comerciais",
    mangoes: "Mangoes",
    name: "Nome",
    next: "Próximo",
    noResults: "Nenhum resultado encontrado",
    of: "de",
    perfectPlatform:
      "A plataforma perfeita para PMEs e empreendedores que desejam levar seus negócios para o próximo nível",
    plan: "Plano",
    plans: "Planos",
    previous: "Anterior",
    pricing: "Preços",
    pricingDescription:
      "Nossos planos são projetados para oferecer a você as ferramentas e o suporte necessários para expandir seus negócios. Se você está apenas começando ou procurando expandir sua empresa, temos a opção perfeita para você. Escolha o plano que melhor atenda às suas necessidades e comece a aproveitar os benefícios desde o primeiro dia.",
    professionalDesigns: "Designs profissionais",
    products: "Produtos",
    publishAndSell:
      "Publique sua loja e comece a vender para clientes em todo o país",
    purchaseOrders: "Pedidos de Compra/Venda",
    purchaseReceipts: "Recibos de Compra/Venda",
    purchases: "Despesas",
    purchasesInvoices: "Faturas de compra",
    refreshTable: "Atualizar tabela",
    registerAndChoosePlan:
      "Registre-se no Mangoes e escolha o plano que melhor atenda às suas necessidades",
    sales: "Receita",
    salesInvoices: "Faturas de vendas",
    search: "Pesquisar",
    selected: "Selecionado",
    selectTemplate:
      "Selecione um modelo e personalize-o com seus produtos e agência",
    settings: "Configuração",
    showing: "Mostrando",
    signIn: "Login",
    signUp: "Criar conta",
    someBusinessesUsing: "Algumas empresas usando Mangoes",
    startNow: "Começar",
    support247: "Suporte 24/7",
    team: "Equipe",
    to: "a",
    toolsOtol: "Ferramentas OTOL",
    whyChoose: "Por que escolher Mangoes?",
  },
};
